"$schema" = 'https://starship.rs/config-schema.json'

format = '$character$directory$git_branch'

[character]
success_symbol = '[➜](green)'
error_symbol = '[✗](red)'
format = '$symbol  '

[directory]
truncation_length = 1
format = '[$path](cyan) '

[git_branch]
format = '[git:\(](blue)[$branch](red)[\)](blue) '